# -*- coding: utf-8 -*-
"""RP_final_G11_method_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1putpjiywNMHUYXRpv_H3oO32-74QHxbs
"""

from copy import copy
import numpy as np
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

#define constants 
Ru = 8.3145
Mwco = 28e-3;
Mwco2 =44e-3;
Mwo2 = 32e-3;
Mwh2o = 18e-3;
Mwn2 = 28e-3;
V=67.4e-6; # dia 50 mm 
P = 1e5;

hf0co = -110541/Mwco #110541/Mwco;
hf0co2= -393546/Mwco2; #393546/Mwco2;
hf0h2o = -241845/Mwh2o; #241845/Mwh2o;
hf0o2 = 0;
hf0n2 = 0;
Cpo2 = 37.788/Mwo2;
Cph2o =  51.143/Mwh2o;
Cpco = 36.271/Mwco #1294;
Cpco2 = 60.433/Mwco2 ;
Cpn2 = 35.988/Mwn2;

# get inlet conditions
r = 2/100;
xh2o = r;
xo2 = (1-r)/(1+2+ (0.79/0.21))
xco = 2*xo2;
xn2 = 0.79*xo2/0.21;
Mwmix0 = (xo2*Mwo2 + xn2*Mwn2 + xco*Mwco + xh2o*Mwh2o)

yn2in = xn2*Mwn2/Mwmix0; yn2=yn2in;
yo2in = xo2*Mwo2/Mwmix0;
yh2o = xh2o*Mwh2o/Mwmix0;
yh2oin = yh2o;
ycoin = xco*Mwco/Mwmix0; 




# define necessary functions
def kr(T): 
    return (5e8)*np.exp( -1.674*10**5/(Ru*T))

def kf(T):
    return (2.24e12)*(1000**(-0.75))*np.exp( -1.674*10**5/(Ru*T))


def Mwmix(yh2o,yco,yco2,yo2,yn2):
    return 1/((yco/Mwco) + (yco2/Mwco2) + (yo2/Mwo2) + (yh2o/Mwh2o) + (yn2/Mwn2))

def con(MWmix,y,MW,T):
    return (P*MWmix/(Ru*T))*y/MW
    
def wdco(yh2o,yco,yco2,yo2,T):
    MW=Mwmix(yh2o,yco,yco2,yo2,yn2);
    Cco2=con(MW,yco2,Mwco2,T);
    Cco=con(MW,yco,Mwco,T);
    Ch2o=con(MW,yh2o,Mwh2o,T);
    Co2=con(MW,yo2,Mwo2,T);
    dw=kr(T)*Cco2 - kf(T)*Cco*(Ch2o**0.5)*(Co2**0.25)
    #print(dw)
    return dw


# define the 4 governing equations
def f1(yh2o,yco,yco2,yo2,T,mdot,ycoin):
    return mdot*(yco - ycoin) - wdco(yh2o,yco,yco2,yo2,T)*Mwco*V

#def f2(yh2o,yco,yco2,yo2,T,mdot,yo2in):
#    return mdot*(yo2 - yo2in) - wdco(yh2o,yco,yco2,yo2,T)*Mwo2*V

def f2(yh2o,yco,yco2,yo2,T,mdot,yo2in):
    return mdot*(0 - yco2) - wdco(yh2o,yco,yco2,yo2,T)*Mwco2*V

def f3(yh2o,yco,yco2,yo2,yn2):
    return yco + yo2 + yco2 + yh2o + yn2 - 1 

Tin=298;
def f4(yh2o,yco,yco2,yo2,yn2,mdot,T):
    return (yh2o*(hf0h2o + Cph2o*(T-298)) + yco*(hf0co + Cpco*(T-298)) + yco2*(hf0co2 + Cpco2*(T-298)) + yo2*(hf0o2 + Cpo2*(T-298)) + yn2*(hf0n2 + Cpn2*(T-298))  - yh2oin*(hf0h2o + Cph2o*(Tin-298)) - yo2in*(hf0o2 + Cpo2*(Tin-298)) - ycoin*(hf0co + Cpco*(Tin-298))- yn2in*(hf0n2 + Cpn2*(Tin-298)))


def function(x,dm,T):
  n=len(x); f=np.zeros([n,1])
  yco=x[0]; yo2=x[1]; yco2=x[2];
  f[0]=f1(yh2o,yco,yco2,yo2,T,dm,ycoin);
  f[1]=f2(yh2o,yco,yco2,yo2,T,dm,yo2in);
  f[2]=f3(yh2o,yco,yco2,yo2,yn2);
  return(f)

def Newton_NL(x0,dm,T):
    n=len(x0); 
    x=copy(x0); k=0;
    dfdx=np.zeros([n,n]);
    while True:
        k=k+1;
        f=function(x,dm,T);
        for i in range(n):
            for j in range(n):
                dfdx[i,j]=pde(init,dm,i,j,T)
        delta=np.linalg.solve(dfdx,-f);
        x=x+delta; ch=delta/(x);       
        norm=sum(abs(f));
        norm_new=sum(abs(function(x+delta,dm,T)));
        if norm_new>norm:
           delta=delta/5;
        else:
           delta=delta;
        if np.all(abs(x) >= 1e-7):
            if np.all(abs(ch)<=1e-7):
                break;
        else:
            if np.all(abs(delta)<=1e-7):
                break;        
    return(x,k)

def pde(x,dm,i,j,T):
    if abs(x[j])>1:
        ep=abs(x[j])*1e-5;
    else:
        ep=1e-5
    x1=copy(x); x1[j]=x1[j]+ep;
    F1=function(x1,dm,T);
    F=function(x,dm,T);
    dfdx=(F1[i]-F[i])/ep;
    return(dfdx)

#yco=x[0]; yo2=x[1]; yco2=x[2];

init=[1e-2,1e-2,4.1e-2] # initial guess value
def one_iter(dm,T):
    x0=np.array([init],dtype=float).T;
    x=np.zeros([len(init),1]); f=np.zeros([len(init),1]); 
    sol1=Newton_NL(x0,dm,T);
    sol2=function(sol1[0],dm,T);
    for j in range(len(init)):
        x[j]=sol1[0][j] 
        f[j]=sol2[j] 
    return x

Temps = np.linspace(2500,1500,100)
def Feval(dm,Temps):
    X = []; Tr=[];
    for i in range(len(Temps)):
        z = one_iter(dm,Temps[i])
        yco=z[0]; yo2=z[1]; yco2=z[2];
        sol_f4=f4(yh2o,yco,yco2,yo2,yn2,mdot,Temps[i])[0]
        X.append(sol_f4); Tr.append(Temps[i]); 
        if sol_f4<0:
            break
    X=np.asarray(X); Tr=np.asarray(Tr);
    return [X,Tr,z]

dm=np.linspace(1e-6,0.5,250);

#yco=x[0]; yo2=x[1]; yco2=x[2];
X=[]; Tr=[]; Yco=[]; Yo2=[]; Yco2=[]; T=[]; mdot=[]; #final values
for i in range(len(dm)):
    sol=Feval(dm[i],Temps)
    X.append(sol[0]); Tr.append(sol[1]);
    if all(X[i]>0): #blowout criteria
        break
    else:
        mdot.append(dm[i]);
        f_interp = interp1d(X[i],Tr[i], kind = 'cubic')
        T.append(f_interp(0));#np.interp(0, X[i], Tr[i])) 
        Yco.append(sol[2][0]);
        Yo2.append(sol[2][1]);
        Yco2.append(sol[2][2]);

plt.figure(1)
plt.plot(Temps,np.zeros([len(Temps)]))
for i in range(len(X)):
    plt.plot(Tr[i],X[i],"-o")
plt.ylabel("function 4 (energy equation)")
plt.xlabel("Temps (K)")
plt.grid()
 
    
plt.figure(2)
plt.plot(mdot,Yco,"-o")
plt.ylabel(" Yco")
plt.xlabel("mass flow rate (kg/s)")
plt.grid()

plt.figure(3)
plt.plot(mdot,Yo2,"-o")
plt.ylabel(" Yo2")
plt.xlabel("mass flow rate (kg/s)")
plt.grid()

plt.figure(4)
plt.plot(mdot,Yco2,"-o")
plt.ylabel(" Yco2")
plt.xlabel("mass flow rate (kg/s)")
plt.grid()
    
plt.figure(5)
plt.plot(mdot,T,"-o")
plt.ylabel("Temperature (K)")
plt.xlabel("mass flow rate (kg/s)")
plt.grid()

plt.show()   


print(mdot[-1])
print(T[-1])